#!/bin/bash 

source ../../utils.sh

# Check the number of arguments
if [ $# -ne 1 ]; then
    print_error "Please provide a project name"
    print_info "Usage: ./script.sh <project name>"
    exit 1
fi

project_name=$1
nbr_warning=0

project_setup_verification $project_name

cd "$KALDI_INSTALLATION_PATH/egs/$project_name"

print_info "The current directory is $KALDI_INSTALLATION_PATH/egs/$project_name"

print_info "Delete all containt which are in data/lang"
rm -f data/lang/*
rm -f data/lang/*/
print_info "Delete file align_lexicon.txt, lexiconp.txt, lexiconp_disambig.txt, lex_ndisambig and phone_map.txt which are in data/local"
# echo "*************** $?"
delete_file data/local/align_lexicon.txt 1
nbr_warning=$(( $? == 0 ? nbr_warning + 1 : nbr_warning ))
delete_file data/local/lexiconp.txt 0
nbr_warning=$(( $? == 0 ? nbr_warning + 1 : nbr_warning ))
delete_file data/local/lexiconp_disambig.txt 0
nbr_warning=$(( $? == 0 ? nbr_warning + 1 : nbr_warning ))
delete_file data/local/lex_ndisambig 0
nbr_warning=$(( $? == 0 ? nbr_warning + 1 : nbr_warning ))
delete_file data/local/phone_map.txt 0
nbr_warning=$(( $? == 0 ? nbr_warning + 1 : nbr_warning ))


print_info "Delete file lexiconp.txt which is data/local/lang"

delete_file data/local/lang/lexiconp.txt 0
# rm -f $KALDI_INSTALLATION_PATH/egs/$project_name/data/local/lang/lexiconp.txt

print_info "End of deletion of files and folders contained in the local and lang folders automatically generated by kaldi in the $project_name project. \033[1;33m Warning Number = $nbr_warning \033[0m"
